<?php
/**
 * Created by PhpStorm.
 * User: marlb
 * Date: 02.05.2017
 * Time: 22:03
 */

namespace app\models;


use yii\db\ActiveRecord;

class Category extends ActiveRecord
{

    public static function tableName()
    {
        //return 'oc_category_description';
        return 'oc_category';
        //  return parent::tableName(); // TODO: Change the autogenerated stub
    }

    public function getProductsId()
    {
        return $this->hasMany(ProductToCategory::className(), ['category_id' => 'category_id']);
    }

}