<?php
/**
 * Created by PhpStorm.
 * User: marlb
 * Date: 25.04.2017
 * Time: 23:36
 */

namespace app\models;


use yii\db\ActiveRecord;


class TestForm extends ActiveRecord
{

//    public $name;
//    public $email;
//    public $text;

    public static function tableName()
    {
        return 'posts';
    }

    public function attributeLabels()
    {
        return [
            'name' => 'Имя',
            'email' => 'E-mail',
            'text' => 'Текст Собщения',
        ];
        //return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }


    public function rules()
    {
        return [
            [['name', 'text'], 'required'],
            ['email', 'email'],

//            ['text', 'trim'],
//            [['name', 'email'], 'required'],
//            ['name', 'string', 'min' => 2, 'tooShort' => 'Мало'],
//            ['name', 'string', 'max' => 5, 'tooLong' => 'Много'],

//            ['name', 'string', 'length' => [2, 5]],
//            ['name', 'myRule'],

//            ['text', 'safe'], // не проверяет поле
        ];
        //   return parent::rules(); // TODO: Change the autogenerated stub
    }

//    public function myRule($attr)
//    {
//
//        if (!in_array($this->$attr, ['hello', 'world'])) {
//            $this->addError($attr, 'Wrong!');
//        }
//
//    }

}